telegram:
  bot:
    username: ${BOT_NAME}
    token: ${BOT_TOKEN}

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT

app:
  notification:
    price-check-interval: 120000
    min-notification-interval: 600000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver